from .dorefa import DoReFaFakeQuantize
from .dsq import DSQFakeQuantize
from .fixed import FixedFakeQuantize
from .lsq import LearnableFakeQuantize
from .nnie import NNIEFakeQuantize
from .pact import PACTFakeQuantize
from .tqt import TqtFakeQuantize
from .adaround_quantizer import AdaRoundFakeQuantize
from .qdrop_quantizer import QDropFakeQuantize